# Generated by Django 4.1.1 on 2022-09-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_art',
            new_name='created_at',
        ),
    ]
